apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-api-deployment
spec:
  selector:
    matchLabels:
      app: voting-api
  template:
    metadata:
      labels:
        app: voting-api
    spec:
      containers:
      - name: voting-api
        image: benny0329/voting-api
        env:
          - name: MONGO_URI
            value: "mongodb://voting-api-mongo:27017/voting"
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key:  JWT_KEY
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
